// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OxenteBurguer.Data;

#nullable disable

namespace OxenteBurguer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505021347_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("OxenteBurguer.Models.Pedido", b =>
                {
                    b.Property<int>("NumeroPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("NumeroPedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("OxenteBurguer.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PedidoNumeroPedido")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PedidoNumeroPedido");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OxenteBurguer.Models.Lanche", b =>
                {
                    b.HasBaseType("OxenteBurguer.Models.Produto");

                    b.PrimitiveCollection<string>("Adicionais")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PontoCarne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Lanche");
                });

            modelBuilder.Entity("OxenteBurguer.Models.Produto", b =>
                {
                    b.HasOne("OxenteBurguer.Models.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoNumeroPedido");
                });

            modelBuilder.Entity("OxenteBurguer.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
